# -*- coding: utf-8 -*-
"""Te damos la bienvenida a Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb

# Clase con la profesora-Ejercicio con el operador punto

Miercoles 17 de Febrero 2026
"""

#@autor:arizbesilva0-star #Cuenta.py
class Cuenta :
  #este es el metodo constructor, que
  #inicializa a los atributos de una clase
  def __init__(self, valor) :
    self.saldo=valor

# Menu.py
class Menu:
  pass
print("Desde el Menu")
cuenta1=Cuenta(3000,)
print(cuenta1.saldo)