# -*- coding: utf-8 -*-
"""Tarea_1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ltvPNfjCpAchXZZ_ogJVD3Azqf7HKdAf
"""

#Ejercicio 1
#Hacer que el programa que resuelve la ecuación cuadratica,
#tenga solución cuando el discriminante sea menor a cero.

a=float(input('Da tu coeficiente a: '))
b=float(input('Da tu coeficiente b: '))
c=float(input('Da tu coeficiente c: '))

dis=b**2-4*a*c #Discriminante

if a!=0:
    if dis<0:
        print("Las soluciones son complejas")
        xr = -b/(2*a)
        xi = ((-dis)**(0.5))/(2*a)
        print("x1= ", xr, "+", xi, "i")
        print("x2= ", xr, "-", xi, "i")

    elif dis>0:
        print("Hay dos soluciones reales")
        x1=(-b + (dis**(0.5))) / (2*a)
        x2=(-b - (dis**(0.5))) / (2*a)
        print("x1= ", x1)
        print("x2= ", x2)

    elif dis==0:
        print("La solución real es única")
        x=-b/(2*a)
        print("x= ",x)

elif a == 0:  # Si a es 0, la ecuación se vuelve lineal: bx + c = 0
    if b != 0:
        print("La ecuación es lineal y tiene una solución")
        x = -c/b
        print("x = ", x)
    else: #a = 0 y b = 0
        if c == 0:
            print("Soluciones infinitas")
        else:
            print("Contradicción")

#Ejercicio 2
#Desarrollar un programa que calcule la suma de los dígitos
# de cualquier número entero positivo introducido por el usuario

n=int(input('Da un número entero positivo: '))

if n>=0:
    suma=0

    while n>0:
        dig=n%10      # obtiene el último dígito
        suma=suma+dig # se suma el dígito
        n=n//10

    print("La suma de los dígitos es: ", suma)

else:
    print("El número debe ser positivo")

#Ejercicio 3
palabra=input('Da una palabra: ')

invertida=palabra[::-1]

if palabra==invertida:
    print("La palabra es un palíndromo")
else:
    print("La palabra no es un palíndromo")

#Ejercicio 4
#Escribir un programa que pida al usuario una palabra
# y muestre por pantalla si es un palíndromo.

import random

suma=0
print("Sucesión de números:")

while suma<1.50:
    num=random.uniform(0.01,0.20)

    if suma+num<1.50:
        suma=suma+num
        print(num)
    else:
        break

print("La suma total es: ", suma)

#Ejercicio 5
#i. Construye un programa que diga si un número entero es o no primo

n=int(input('Da un número entero: '))

if n<=1:
    print("El número no es primo")
else:
    i=2
    primo=True
    while i<n:
        if n%i==0:
            primo=False
        i=i+1
    if primo==True:
        print("El número es primo")
    else:
        print("El número no es primo")

#ii. Elabora un programa que muestre los primeros N números primos.

N=int(input('¿Cuántos números primos deseas ver?: '))

contador=0
num=2
while contador<N:
    i=2
    primo=True
    while i<num:
        if num%i==0:
            primo=False
        i=i+1
    if primo==True:
        print(num)
        contador=contador+1

    num=num+1

#Ejecicio 6
#Haz un programa que te regrese los primeros 100 términos
#de la sucesión de Fibonacci (1, 1, 2, 3, 5, 8, 13, 21, 34, 55, · · ·)

a=1
b=1
contador=0

print("Los primeros 100 términos de Fibonacci son:")

while contador<100:
    print(a)

    c=a+b
    a=b
    b=c

    contador=contador+1