# -*- coding: utf-8 -*-
"""tarea_3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lVpmpK9NXh8Oe5m_P-9_-XOt9nCaLWiO
"""

"""
Integrantes del equipo:

Silva Silva Arizbe Itzari
González Hernández Isai
"""

'''
Created on March, 2026
@author: isaighernandez, arizbesilva0-star
'''

class Playlist:
  def __init__(self,nombre):
    self.nombre = nombre
    self.canciones=[]

  def añadir_cancion(self,titulo):
    if len(self.canciones) >= 5:
      print("Alcanzante el limite maximo de canciones por playlist")
    else:
      if titulo in self.canciones:
        print("La canción ya se encuentra en la playlist")
      else:
        self.canciones.append(titulo)
        print(f"{titulo} añadida a {self.nombre}.")

  def eliminar_cancion(self,titulo):
    if titulo in self.canciones:
      self.canciones.remove(titulo)
      print(f"{titulo} ha sido eliminado de {self.nombre}")
    else:
      print(f"{titulo} no esta en {self.nombre}")

  def total_canciones(self):
    return len(self.canciones)

  def mostrar_playlist(self):
    print(f"========== Playlist: {self.nombre} ==========")
    if len(self.canciones) == 0:
      print("La Playlist esta vacia actualmente")
    else:
      i = 1
      for titulo in self.canciones:
        print(i,titulo)
        i += 1

  def limpiar_playlist(self):
    self.canciones.clear()
    print("La playlist esta vacia")

  def buscador(self,texto):
    encontrados = []

    texto = texto.strip().lower()

    for cancion in self.canciones:
        cancion_limpia = cancion.lower().strip()

        if texto in cancion_limpia:
            encontrados.append(cancion)

    if len(encontrados) > 0:
        print(f"Canciones relacionadas con '{texto}' en {self.nombre}:")
        for cancion in encontrados:
            print(cancion)
    else:
        print(f"No hay canciones relacionadas con '{texto}' en la playlist {self.nombre}")

mix_pop = Playlist("Mi musica de Rock")

mix_pop.añadir_cancion("Enjoy The Silence")

mix_pop.añadir_cancion("Personal Jesus")

mix_pop.añadir_cancion("Policy of Truth")

mix_pop.añadir_cancion("Policy of Truth")

mix_pop.añadir_cancion("World in My Eyes")

mix_pop.mostrar_playlist()

mix_pop.añadir_cancion("Precious")

mix_pop.añadir_cancion("People Are People")

mix_pop.mostrar_playlist()

mix_pop.buscador("Per")

mix_pop.buscador("Jesu")

mix_pop.buscador("perso")

mix_pop.buscador("WORLD ")

mix_pop.buscador("  the ")

mix_pop.buscador("the ")

mix_pop.limpiar_playlist()