# -*- coding: utf-8 -*-
"""teoria

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eYvpCG-EQndqa2hWS6O6fVeQcZWD2mVF

# Clase con la profesora-Ejercicio depositar
Jueves 19 de Febrero 2026
"""

#@autor:arizbesilva0-star  #Cuenta.py
class Cuenta :
  #este es el metodo constructor, que
  #inicializa a los atributos de una clase
  def __init__(self, valor, tipo) :
    self.saldo=valor
    self.tipo=tipo

# Menu.py
class Menu:
  pass
print("Desde el Menu")
cuenta1=Cuenta(3000, "c")
print(cuenta1.saldo)
print(cuenta1.tipo)

"""Ahora en esta clase agregaremos el metodo de depositar.

"""

#@autor:arizsil #Cuenta.py
class Cuenta :
  #este es el metodo constructor, que
  #inicializa a los atributos de una clase
  def __init__(self, valor1, valor2) :
    self.saldo=valor1
    self.tipo=valor2
  def depositar(self, cantidad) :
    self.saldo=self.saldo+cantidad
  def retirar(self, cantidad2) :
    self.saldo=self.saldo-cantidad2

# Menu.py
class Menu:
  pass
print("Probando el objeto")
cuenta1=Cuenta(3000, "c")
print(cuenta1.saldo)
print(cuenta1.tipo)
cuenta1.depositar(5000)
print("Pobando el deposito")
print(cuenta1.saldo)
cuenta1.retirar(1200)
print("Probando el retiro")
print(cuenta1.saldo)