# -*- coding: utf-8 -*-
"""Cliente

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IVKHqyaII1qolaajxjqslWkWaroigf7p
"""

"""
Created on Febrero, 2019
@author: arizbesilva0-star
"""

class Cliente:

    def __init__(self, nombre, cuenta):
        self.nombre = nombre
        self.cuenta = cuenta

    def __str__(self):
        return "Cliente: " + self.nombre + " | " + str(self.cuenta)