# -*- coding: utf-8 -*-
"""mi-proyecto.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1feWYAKBxrXDddFLTNZtNWfmPLK1UlCDh

# Sistema de Inversiones
"""

#@autor:arizsil #Inversion.py
class Inversion :
    #este es el metodo constructor, que
    #inicializa a los atributos de una clase
    def __init__(self, valor1, valor2, valor3, valor4) :
        self.capital = valor1       #dinero invertido
        self.interes = valor2       #tasa de interes
        self.tiempo = valor3        #tiempo de inversion
        self.nombre = valor4        #nombre de la inversion

    def aumentar(self, cantidad) :
        self.capital = self.capital + cantidad

    def disminuir(self, cantidad2) :
        self.capital = self.capital - cantidad2

#metodo que calcula el monto final de la inversion
    def calcular(self) :
        self.capital = self.capital * self.interes * self.tiempo

    def mostrar(self) :
        print(self.nombre)

# Menu.py
class Menu:
    pass

print("Desde el Menu")

inversion1 = Inversion(1000, 0.05, 12, "Inversion Banco BBVA")

print(inversion1.capital)
print(inversion1.interes)
print(inversion1.tiempo, "meses")
print(inversion1.nombre)

inversion1.aumentar(500)
print("Probando el aumento")
print(inversion1.capital)

inversion1.disminuir(120)
print("Probando la disminucion")
print(inversion1.capital)

inversion1.calcular()
print("Probando el calculo")
print(inversion1.capital)